name: Deployement pipeline

on: push

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_USER: 'backend_user'
          POSTGRES_PASSWORD: 12345
          POSTGRES_DB: recettes
        ports: 
          - 5432:5432

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: |
          cd ./projet_frontend/
          npm install

      - name: Install backend dependencies
        run: |
          cd ./projet_backend/
          npm install

      - name: Fix frontend vulnerabilities
        run: |
          cd ./projet_frontend/
          npm audit fix

      - name: Fix backend vulnerabilities
        run: |
          cd ./projet_backend/
          npm audit fix

      - name: Migrate PostgreSQL
        run: |
          PGPASSWORD=12345 psql -h localhost -U backend_user -d recettes -f projet_bdd/01_creer_bd.sql
          PGPASSWORD=12345 psql -h localhost -U backend_user -d recettes -f projet_bdd/02_creer_user.sql
          PGPASSWORD=12345 psql -h localhost -U backend_user -d recettes -f projet_bdd/03_recettes.sql
          PGPASSWORD=12345 psql -h localhost -U backend_user -d recettes -f projet_bdd/04_recettes_insertion_donnees.sql
          PGPASSWORD=12345 psql -h localhost -U backend_user -d recettes -f projet_bdd/05_grant_backend_user.sql
          PGPASSWORD=12345 psql -h localhost -U backend_user -d recettes -f projet_bdd/06_creer_utilisateurs.sql
        env:
          POSTGRES_USER: 'backend_user'
          POSTGRES_PASSWORD: 12345
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

      - name: Run build
        run: |
          cd ./projet_frontend/
          npm run build
          
      - name: Jest test
        run: |
          cd ./projet_backend/
          npm run test --coverage

      - name: Run eslint
        run: npm run lint

      - name: Coveralls
        uses: coverallsapp/github-action@master
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}